/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:e255ac99-fe71-43bb-9513-52003ce3be44",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_hDypHWRkx",
    "aws_user_pools_web_client_id": "1ok9ef811on242i6h9osg4o4uf",
    "oauth": {}
};


export default awsmobile;
